/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.swrookie;

import java.io.IOException;
import com.opencsv.exceptions.CsvException;
import com.swrookie.producer.JsonProducer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, CsvException {
        // System.out.println(new App().getGreeting());
        var producer = new JsonProducer();
    }
}
